name: Create 3D World

on:
  push:
    branches:
      - main

jobs:
  create_world:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install Blender
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        
    - name: Install Blender-OSM Add-on
      run: |
        pip install bpy
        blender --background --python-text "import bpy; bpy.ops.wm.addon_install(filepath='https://github.com/vvoovv/blender-osm/archive/master.zip')"
        
    - name: Create 3D World
      run: |
        blender --background --python-text "import bpy; bpy.ops.import_scene.osm(filepath='map.osm')"
        
    - name: Export 3D World
      run: |
        blender --background --python-text "import bpy; bpy.ops.export_scene.obj(filepath='world.obj')"

    - name: Upload 3D World
      uses: actions/upload-artifact@v2
      with:
        name: 3d-world
        path: world.obj
