name: Create 3D World

on:
  push:
    branches:
      - main

jobs:
  create_world:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install Blender
      run: |
        wget https://download.blender.org/release/Blender2.93/blender-2.93.1-linux-x64.tar.xz
        tar -xf blender-2.93.1-linux-x64.tar.xz
        
    - name: Create 3D World
      run: |
        ./blender-2.93.1-linux-x64/blender --background --python-text "import bpy; bpy.ops.import_scene.osm(filepath='map.osm')"
        
    - name: Export 3D World
      run: |
        ./blender-2.93.1-linux-x64/blender --background --python-text "import bpy; bpy.ops.export_scene.obj(filepath='world.obj')"

    - name: Upload 3D World
      uses: actions/upload-artifact@v2
      with:
        name: 3d-world
        path: world.obj
