name: OSM to OBJ Conversion

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install Blender
      run: |
        sudo snap install blender --classic
    
    - name: Install Blender-blosm addon
      run: blender --background --python-expr "import bpy; bpy.ops.preferences.addon_install(filepath='./blosm.zip')"
    
    - name: Convert OSM to OBJ
      run: blender --background --python "convert.py"
    
    - name: Upload OBJ artifact
      uses: actions/upload-artifact@v2
      with:
        name: converted-obj
        path: map.obj
