name: OSM to OBJ Conversion

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install Blender
      uses: ankitsejwal/blender-installer-action@v1
      with:
        blender-version: '2.93.4'
    
    - name: Extract blosm addon
      run: |
        unzip blosm.zip -d blosm
    
    - name: Enable blosm addon
      run: |
        mkdir -p $HOME/.config/blender/2.93/scripts/addons/
        cp -r blosm $HOME/.config/blender/2.93/scripts/addons/

    - name: Run Blender
      run: |
        blender-2.93.4-linux-x64/blender --background --python-expr "import bpy; bpy.ops.preferences.addon_enable(module='blosm')"
        blender-2.93.4-linux-x64/blender --background --python-expr "import bpy; bpy.ops.import_scene.osm(filepath='map.osm')"
        blender-2.93.4-linux-x64/blender --background --python-expr "import bpy; bpy.ops.export_scene.obj(filepath='world.obj')"

    - name: Upload OBJ artifact
      uses: actions/upload-artifact@v2
      with:
        name: 3d-world
        path: world.obj
