name: OSM to OBJ Conversion

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install Snap
      run: sudo apt update && sudo apt install -y snapd
    
    - name: Install Blender
      run: sudo snap install blender --classic

    - name: Download OSM file
      run: wget https://example.com/path/to/map.osm -O map.osm

    - name: Convert OSM to OBJ
      run: blender --background --python "convert.py"
    
    - name: Upload OBJ artifact
      uses: actions/upload-artifact@v2
      with:
        name: converted-obj
        path: path/to/obj/

