name: Blosm OBJ Conversion

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Blender
      uses: ankitsejwal/blender-installer-action@v1
      with:
        blender-version: 2.93.1

    - name: Download Blosm addon
      run: |
        wget -O blosm.zip https://app.gumroad.com/r/2208af38ae0291722df0f3cd36ee6e05/d50aLBM2bGyZ-WSIeXjqqA==
        unzip blosm.zip -d blosm
        
    - name: Run Blender with Blosm addon
      run: |
        ./blender-2.93.1-linux-x64/blender --background --python blosm/addon/__init__.py --python-expr "import bpy; bpy.ops.blosm.import_osm()"
      
    - name: Upload OBJ artifact
      uses: actions/upload-artifact@v2
      with:
        name: converted-obj
        path: output.obj
