name: OSM to OBJ Conversion

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install JDK
        uses: actions/setup-java@v2
        with:
         distribution: 'adopt'
         java-version: '20'
        
      - name: Download and extract OSM2World
        run: |
          wget https://osm2world.org/download/files/latest/OSM2World-latest-bin.zip
          unzip OSM2World-latest-bin.zip -d OSM2World
          cd OSM2World
          chmod +x osm2world.sh

      - name: Install Osmosis
        run: |
          wget https://bretth.dev.openstreetmap.org/osmosis-build/osmosis-latest.zip
          unzip OSM2World-latest-bin.zip

      - name: Convert OSM to OBJ
        run: |
          ./osmosis-latest/bin/osmosis \
            --read-xml file="*.osm" \
            --tag-filter accept-ways building=* \
            --tag-filter reject-relations \
            --used-node \
            --bounding-polygon file="manhattan_new-york.poly.txt" \
            --write-xml file="manhattan-buildings.osm"
          ./osm2world-*/osm2world.sh -i manhattan-buildings.osm -o manhattan.obj

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: converted-3d-model
          path: manhattan.obj
