name: OSM to OBJ Conversion

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '20'

    - name: Download and extract OSM2World
      run: |
        wget https://osm2world.org/download/files/latest/OSM2World-latest-bin.zip
        unzip OSM2World-latest-bin.zip -d OSM2World
        cd OSM2World
        chmod +x osm2world.sh

        # Add the texture directory and configuration to the OSM2World directory
        mkdir textures
        cp /path/to/your/textures/* textures/
        echo "texture.path = textures/" >> config.properties
        
        ./osm2world.sh -i ../map.osm -o ../map.obj

    - name: Upload OBJ artifact
      uses: actions/upload-artifact@v2
      with:
        name: converted-obj
        path: map.obj
