name: OSM2World Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run OSM2World
        run: |
          wget https://osm2world.org/download/osm2world-latest.zip
          unzip osm2world-latest.zip
          java -jar OSM2World/osm2world.jar -i map.osm -o map.obj

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: OBJ File
          path: map.obj
